### ISSUE TITLE
Strange message (state='') displayed

### ISSUE THREAD

**Issue by aoyama-val** [labocho/thor-zsh_completion#4]
When sourced the generated completion script, a strange message appears on the terminal.

```
state=''
```

This is caused by the line `local state` on top of the script. Is it possible to omit it?

**Comment by labocho** [comment]
When I source script twice (or more), the message seems to appear.
I think `local state` is unnecessary. I removed it ( 61c0d665fa6039515de0f3c23d61d2cca41210f6 , v0.1.5) .
Thank you for reporting!
